name: npd_traffic_count_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dropdownfield: ^1.0.3

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  responsive_framework: ^0.2.0
  google_fonts: ^2.3.1
  dots_indicator: ^2.1.0
  font_awesome_flutter: ^10.1.0
  font_awesome: ^5.10.1
  http: ^0.13.4
  rflutter_alert: ^2.0.4
  provider: ^6.0.2
  geolocator: ^8.0.5

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"

  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/

flutter_icons:
     image_path:  "assets/logos/Traffic5.png"
     android: true
     ios: true
     remove_alpha_ios: true 

